sudo: required

language: nodejs

node_js:
  - "10"

services:
  - docker

before_install:
  - docker pull mongo:3.4.17-jessie
  - docker run --name mongo1 --rm -d -v $(pwd)/.mongodb:/etc/mongo mongo:3.4.17-jessie --config /etc/mongo/mongod-primary.conf
  - docker run --name mongo2 --rm -d -v $(pwd)/.docker:/etc/mongo mongo:3.4.17-jessie --config /etc/mongo/mongod-secondary.conf
  - sleep 20
